config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "trips#index"
  # Routes for the Expense resource:

  # CREATE
  get("/expenses/new", { :controller => "expenses", :action => "new_form" })
  post("/create_expense", { :controller => "expenses", :action => "create_row" })
  post("/create_expense_from_trip", { :controller => "expenses", :action => "create_row_from_trip" })

  # READ
  get("/expenses", { :controller => "expenses", :action => "index" })
  get("/expenses/:id_to_display", { :controller => "expenses", :action => "show" })

  # UPDATE
  get("/expenses/:prefill_with_id/edit", { :controller => "expenses", :action => "edit_form" })
  post("/update_expense/:id_to_modify", { :controller => "expenses", :action => "update_row" })

  # DELETE
  get("/delete_expense/:id_to_remove", { :controller => "expenses", :action => "destroy_row" })
  get("/delete_expense_from_trip/:id_to_remove", { :controller => "expenses", :action => "destroy_row_from_trip" })

  #------------------------------

  # Routes for the Itinerary resource:

  # CREATE
  get("/itineraries/new", { :controller => "itineraries", :action => "new_form" })
  post("/create_itinerary", { :controller => "itineraries", :action => "create_row" })
  post("/create_itinerary_from_trip", { :controller => "itineraries", :action => "create_row_from_trip" })

  # READ
  get("/itineraries", { :controller => "itineraries", :action => "index" })
  get("/itineraries/:id_to_display", { :controller => "itineraries", :action => "show" })

  # UPDATE
  get("/itineraries/:prefill_with_id/edit", { :controller => "itineraries", :action => "edit_form" })
  post("/update_itinerary/:id_to_modify", { :controller => "itineraries", :action => "update_row" })

  # DELETE
  get("/delete_itinerary/:id_to_remove", { :controller => "itineraries", :action => "destroy_row" })
  get("/delete_itinerary_from_trip/:id_to_remove", { :controller => "itineraries", :action => "destroy_row_from_trip" })
  get("/delete_itinerary_from_traveler/:id_to_remove", { :controller => "itineraries", :action => "destroy_row_from_traveler" })

  #------------------------------

  # Routes for the Trip resource:

  # CREATE
  get("/trips/new", { :controller => "trips", :action => "new_form" })
  post("/create_trip", { :controller => "trips", :action => "create_row" })

  # READ
  get("/trips", { :controller => "trips", :action => "index" })
  get("/trips/:id_to_display", { :controller => "trips", :action => "show" })

  # UPDATE
  get("/trips/:prefill_with_id/edit", { :controller => "trips", :action => "edit_form" })
  post("/update_trip/:id_to_modify", { :controller => "trips", :action => "update_row" })

  # DELETE
  get("/delete_trip/:id_to_remove", { :controller => "trips", :action => "destroy_row" })

  #------------------------------

  devise_for :travelers
  # Routes for the Traveler resource:

  # READ
  get("/travelers", { :controller => "travelers", :action => "index" })
  get("/travelers/:id_to_display", { :controller => "travelers", :action => "show" })

  #------------------------------

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/itinerary_templates/_itineraries_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "itineraries_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :destination_cont, "Destination contains" %>
    <%= f.text_field :destination_cont, :class => "form-control", :placeholder => "Destination contains" %>
  </div>

  <div class="form-group">
    <%= f.label :home_airport_cont, "Home airport contains" %>
    <%= f.text_field :home_airport_cont, :class => "form-control", :placeholder => "Home airport contains" %>
  </div>

  <div class="form-group">
    <%= f.label :departure_flight_cont, "Departure flight contains" %>
    <%= f.text_field :departure_flight_cont, :class => "form-control", :placeholder => "Departure flight contains" %>
  </div>

  <div class="form-group">
    <%= f.label :arrival_flight_cont, "Arrival flight contains" %>
    <%= f.text_field :arrival_flight_cont, :class => "form-control", :placeholder => "Arrival flight contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :traveler_email_cont, "Traveler email contains" %>
    <%= f.text_field :traveler_email_cont, :class => "form-control", :placeholder => "Traveler email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :trip_destination_cont, "Trip destination contains" %>
    <%= f.text_field :trip_destination_cont, :class => "form-control", :placeholder => "Trip destination contains" %>
  </div>

  <div class="form-group">
    <%= f.label :trip_destination_destination_cont, "Trip destination contains" %>
    <%= f.text_field :trip_destination_destination_cont, :class => "form-control", :placeholder => "Trip destination contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/itineraries" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#itineraries_filters">
  Show filters
</a>

app/views/itinerary_templates/edit_form.html.erb
<h1>
  Edit itinerary #<%= @itinerary.id %>
</h1>

<hr>

<form action="/update_itinerary/<%= @itinerary.id %>" method="post">


  <div class="form-group">
    <label for="arrival_flight">
      Arrival flight
    </label>

    <input type="text" id="arrival_flight" name="arrival_flight" class="form-control" value="<%= @itinerary.arrival_flight %>">
  </div>

  <div class="form-group">
    <label for="departure_flight">
      Departure flight
    </label>

    <input type="text" id="departure_flight" name="departure_flight" class="form-control" value="<%= @itinerary.departure_flight %>">
  </div>

  <div class="form-group">
    <label for="home_airport">
      Home airport
    </label>

    <input type="text" id="home_airport" name="home_airport" class="form-control" value="<%= @itinerary.home_airport %>">
  </div>

  <div class="form-group">
    <label for="destination">
      Destination
    </label>

    <input type="text" id="destination" name="destination" class="form-control" value="<%= @itinerary.destination %>">
  </div>

  <div class="form-group">
    <label for="trip_id">
      Trip
    </label>

    <%= select_tag(:trip_id, options_from_collection_for_select(Trip.all, :id, :destination, @itinerary.trip_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update itinerary
  </button>
</form>

<hr>

<a href="/itineraries">
  Go back
</a>

app/views/itinerary_templates/edit_form_with_errors.html.erb
<% if @itinerary.errors.any? %>
  <% @itinerary.errors.full_messages.each do |message| %>
    <div class="alert">
      <%= message %>
    </div>
  <% end %>
<% end %>

<h1>
  Edit itinerary #<%= @itinerary.id %>
</h1>

<hr>

<form action="/update_itinerary/<%= @itinerary.id %>" method="post">


  <div class="form-group">
    <label for="arrival_flight">
      Arrival flight
    </label>

    <input type="text" id="arrival_flight" name="arrival_flight" class="form-control" value="<%= @itinerary.arrival_flight %>">
  </div>

  <div class="form-group">
    <label for="departure_flight">
      Departure flight
    </label>

    <input type="text" id="departure_flight" name="departure_flight" class="form-control" value="<%= @itinerary.departure_flight %>">
  </div>

  <div class="form-group">
    <label for="home_airport">
      Home airport
    </label>

    <input type="text" id="home_airport" name="home_airport" class="form-control" value="<%= @itinerary.home_airport %>">
  </div>

  <div class="form-group">
    <label for="destination">
      Destination
    </label>

    <input type="text" id="destination" name="destination" class="form-control" value="<%= @itinerary.destination %>">
  </div>

  <div class="form-group">
    <label for="trip_id">
      Trip
    </label>

    <%= select_tag(:trip_id, options_from_collection_for_select(Trip.all, :id, :destination, @itinerary.trip_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Update itinerary
  </button>
</form>

<hr>

<a href="/itineraries">
  Go back
</a>

app/views/itinerary_templates/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All itineraries
    </h1>

    <a href="/itineraries/new" class="btn btn-block btn-outline-secondary">
      Add a new itinerary
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "itinerary_templates/itineraries_search_form" %>
  </div>
</div>



<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>
          ID
        </th>

        <th>
          Traveler
        </th>

        <th>
          Arrival flight
        </th>

        <th>
          Departure flight
        </th>

        <th>
          Home airport
        </th>

        <th>
          Destination
        </th>

        <th>
          Trip
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @itineraries.each do |itinerary| %>
      <tr>
        <td>
          <%= itinerary.id %>
        </td>

        <td>
          <% if itinerary.traveler.present? %>
            <a href="/travelers/<%= itinerary.traveler.id %>">
              <%= itinerary.traveler.email %>
            </a>
          <% end %>
        </td>

        <td>
          <%= itinerary.arrival_flight %>
        </td>

        <td>
          <%= itinerary.departure_flight %>
        </td>

        <td>
          <%= itinerary.home_airport %>
        </td>

        <td>
          <%= itinerary.destination %>
        </td>

        <td>
          <% if itinerary.trip.present? %>
            <a href="/trips/<%= itinerary.trip.id %>">
              <%= itinerary.trip.destination %>
            </a>
          <% end %>
        </td>

        <td>
          <%= time_ago_in_words(itinerary.created_at) %> ago
        </td>

        <td>
          <%= time_ago_in_words(itinerary.updated_at) %> ago
        </td>

        <td>
          <a href="/itineraries/<%= itinerary.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>

    <div class="row mb-3">
      <div class="col-md-12">
        <%= paginate @itineraries, theme: "twitter-bootstrap-4" %>
      </div>
    </div>

  </div>
</div>

app/views/itinerary_templates/new_form.html.erb
<h1>
  Add a new itinerary
</h1>


<hr>

<form action="/create_itinerary" method="post">

  <input type="hidden" name="traveler_id" value="<%= current_traveler.id %>">

  <div class="form-group">
    <label for="arrival_flight">
      Arrival flight
    </label>

    <input type="text" id="arrival_flight" name="arrival_flight" class="form-control">
  </div>

  <div class="form-group">
    <label for="departure_flight">
      Departure flight
    </label>

    <input type="text" id="departure_flight" name="departure_flight" class="form-control">
  </div>

  <div class="form-group">
    <label for="home_airport">
      Home airport
    </label>

    <input type="text" id="home_airport" name="home_airport" class="form-control">
  </div>

  <div class="form-group">
    <label for="destination">
      Destination
    </label>

    <input type="text" id="destination" name="destination" class="form-control">
  </div>

  <div class="form-group">
    <label for="trip_id">
      Trip
    </label>

    <%= select_tag(:trip_id, options_from_collection_for_select(Trip.all, :id, :destination, @itinerary.trip_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create itinerary
  </button>
</form>

<hr>

<a href="/itineraries">
  Go back
</a>

app/views/itinerary_templates/new_form_with_errors.html.erb
<% if @itinerary.present? %>
  <% if @itinerary.errors.any? %>
    <% @itinerary.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

<h1>
  Add a new itinerary
</h1>


<hr>

<form action="/create_itinerary" method="post">

  <input type="hidden" name="traveler_id" value="<%= current_traveler.id %>">

  <div class="form-group">
    <label for="arrival_flight">
      Arrival flight
    </label>

    <input type="text" id="arrival_flight" name="arrival_flight" class="form-control" value="<%= @itinerary.arrival_flight %>">
  </div>

  <div class="form-group">
    <label for="departure_flight">
      Departure flight
    </label>

    <input type="text" id="departure_flight" name="departure_flight" class="form-control" value="<%= @itinerary.departure_flight %>">
  </div>

  <div class="form-group">
    <label for="home_airport">
      Home airport
    </label>

    <input type="text" id="home_airport" name="home_airport" class="form-control" value="<%= @itinerary.home_airport %>">
  </div>

  <div class="form-group">
    <label for="destination">
      Destination
    </label>

    <input type="text" id="destination" name="destination" class="form-control" value="<%= @itinerary.destination %>">
  </div>

  <div class="form-group">
    <label for="trip_id">
      Trip
    </label>

    <%= select_tag(:trip_id, options_from_collection_for_select(Trip.all, :id, :destination, @itinerary.trip_id), :class => "form-control") %>
  </div>

  <button class="btn btn-block btn-outline-secondary">
    Create itinerary
  </button>
</form>

<hr>

<a href="/itineraries">
  Go back
</a>

app/views/itinerary_templates/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <h1>
      Itinerary #<%= @itinerary.id %> details
    </h1>

    <div class="row mb-3">
      <div class="col">
        <a href="/itineraries" class="btn btn-block btn-outline-secondary">
          Go back
        </a>
      </div>

      <div class="col">
        <% if current_traveler == @itinerary.traveler %>
          <a href="/itineraries/<%= @itinerary.id %>/edit" class="btn btn-block btn-sm btn-outline-secondary">
            Edit itinerary
          </a>
        <% end %>
      </div>

      <div class="col">
        <% if current_traveler == @itinerary.traveler %>
          <a href="/delete_itinerary/<%= @itinerary.id %>" class="btn btn-block btn-sm btn-outline-secondary">
            Delete itinerary
          </a>
        <% end %>
      </div>
    </div>

    <dl>
      <dt>
        Traveler
      </dt>
      <dd>
        <% if @itinerary.traveler.present? %>
          <a href="/travelers/<%= @itinerary.traveler_id %>">
            <%= @itinerary.traveler.email %>
          </a>
        <% end %>
      </dd>

      <dt>
        Arrival flight
      </dt>
      <dd>
        <%= @itinerary.arrival_flight %>
      </dd>

      <dt>
        Departure flight
      </dt>
      <dd>
        <%= @itinerary.departure_flight %>
      </dd>

      <dt>
        Home airport
      </dt>
      <dd>
        <%= @itinerary.home_airport %>
      </dd>

      <dt>
        Destination
      </dt>
      <dd>
        <%= @itinerary.destination %>
      </dd>

      <dt>
        Trip
      </dt>
      <dd>
        <% if @itinerary.trip.present? %>
          <a href="/trips/<%= @itinerary.trip_id %>">
            <%= @itinerary.trip.destination %>
          </a>
        <% end %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@itinerary.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@itinerary.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>